apiVersion: v1
kind: Service
metadata:
    name: web-market-hl-staging
    namespace: staging
spec:
    type: ClusterIP
    ports:
    - port: 80
      protocol: "TCP"
      targetPort: 3000
    selector:
        app: web-market-hl-staging